CREATE DATABASE chinook VERSION '1.0.0';
USE DATABASE chinook VERSION '1.0.0';

CREATE ROLE admin_role WITH FOREIGN ROLE ROLE_admin;
CREATE ROLE user_role  WITH FOREIGN ROLE ROLE_user;

CREATE SERVER mydb FOREIGN DATA WRAPPER oracle;

CREATE SCHEMA alf SERVER mydb;

IMPORT FOREIGN SCHEMA ALF FROM SERVER mydb INTO alf;

SET SCHEMA alf;

GRANT ALL PRIVILEGES TO admin_role;
